-- ═══════════════════════════════════════════════════════════════════════
--                      CUSTOM PED MODELS DATA
-- Auto-generated from FiveM ped reference. Do not edit manually.
-- Source: https://docs.fivem.net/docs/game-references/ped-models/
-- Image CDN: https://docs.fivem.net/peds/{name}.webp
-- ═══════════════════════════════════════════════════════════════════════

PedModels = {
    -- Ambient female (75)
    { name = "a_f_m_beach_01", label = "Beach 01", category = "Ambient female" },
    { name = "a_f_m_bevhills_01", label = "Bevhills 01", category = "Ambient female" },
    { name = "a_f_m_bevhills_02", label = "Bevhills 02", category = "Ambient female" },
    { name = "a_f_m_bodybuild_01", label = "Bodybuild 01", category = "Ambient female" },
    { name = "a_f_m_business_02", label = "Business 02", category = "Ambient female" },
    { name = "a_f_m_downtown_01", label = "Downtown 01", category = "Ambient female" },
    { name = "a_f_m_eastsa_01", label = "Eastsa 01", category = "Ambient female" },
    { name = "a_f_m_eastsa_02", label = "Eastsa 02", category = "Ambient female" },
    { name = "a_f_m_fatbla_01", label = "Fatbla 01", category = "Ambient female" },
    { name = "a_f_m_fatcult_01", label = "Fatcult 01", category = "Ambient female" },
    { name = "a_f_m_fatwhite_01", label = "Fatwhite 01", category = "Ambient female" },
    { name = "a_f_m_ktown_01", label = "Ktown 01", category = "Ambient female" },
    { name = "a_f_m_ktown_02", label = "Ktown 02", category = "Ambient female" },
    { name = "a_f_m_prolhost_01", label = "Prolhost 01", category = "Ambient female" },
    { name = "a_f_m_salton_01", label = "Salton 01", category = "Ambient female" },
    { name = "a_f_m_skidrow_01", label = "Skidrow 01", category = "Ambient female" },
    { name = "a_f_m_soucent_01", label = "Soucent 01", category = "Ambient female" },
    { name = "a_f_m_soucent_02", label = "Soucent 02", category = "Ambient female" },
    { name = "a_f_m_soucentmc_01", label = "Soucentmc 01", category = "Ambient female" },
    { name = "a_f_m_tourist_01", label = "Tourist 01", category = "Ambient female" },
    { name = "a_f_m_tramp_01", label = "Tramp 01", category = "Ambient female" },
    { name = "a_f_m_trampbeac_01", label = "Trampbeac 01", category = "Ambient female" },
    { name = "a_f_o_genstreet_01", label = "Genstreet 01", category = "Ambient female" },
    { name = "a_f_o_indian_01", label = "Indian 01", category = "Ambient female" },
    { name = "a_f_o_ktown_01", label = "Ktown 01", category = "Ambient female" },
    { name = "a_f_o_salton_01", label = "Salton 01", category = "Ambient female" },
    { name = "a_f_o_soucent_01", label = "Soucent 01", category = "Ambient female" },
    { name = "a_f_o_soucent_02", label = "Soucent 02", category = "Ambient female" },
    { name = "a_f_y_beach_01", label = "Beach 01", category = "Ambient female" },
    { name = "a_f_y_bevhills_01", label = "Bevhills 01", category = "Ambient female" },
    { name = "a_f_y_bevhills_02", label = "Bevhills 02", category = "Ambient female" },
    { name = "a_f_y_bevhills_03", label = "Bevhills 03", category = "Ambient female" },
    { name = "a_f_y_bevhills_04", label = "Bevhills 04", category = "Ambient female" },
    { name = "a_f_y_business_01", label = "Business 01", category = "Ambient female" },
    { name = "a_f_y_business_02", label = "Business 02", category = "Ambient female" },
    { name = "a_f_y_business_03", label = "Business 03", category = "Ambient female" },
    { name = "a_f_y_business_04", label = "Business 04", category = "Ambient female" },
    { name = "a_f_y_clubcust_01", label = "Clubcust 01", category = "Ambient female" },
    { name = "a_f_y_clubcust_02", label = "Clubcust 02", category = "Ambient female" },
    { name = "a_f_y_clubcust_03", label = "Clubcust 03", category = "Ambient female" },
    { name = "a_f_y_eastsa_01", label = "Eastsa 01", category = "Ambient female" },
    { name = "a_f_y_eastsa_02", label = "Eastsa 02", category = "Ambient female" },
    { name = "a_f_y_eastsa_03", label = "Eastsa 03", category = "Ambient female" },
    { name = "a_f_y_epsilon_01", label = "Epsilon 01", category = "Ambient female" },
    { name = "a_f_y_femaleagent", label = "Femaleagent", category = "Ambient female" },
    { name = "a_f_y_fitness_01", label = "Fitness 01", category = "Ambient female" },
    { name = "a_f_y_fitness_02", label = "Fitness 02", category = "Ambient female" },
    { name = "a_f_y_genhot_01", label = "Genhot 01", category = "Ambient female" },
    { name = "a_f_y_golfer_01", label = "Golfer 01", category = "Ambient female" },
    { name = "a_f_y_hiker_01", label = "Hiker 01", category = "Ambient female" },
    { name = "a_f_y_hippie_01", label = "Hippie 01", category = "Ambient female" },
    { name = "a_f_y_hipster_01", label = "Hipster 01", category = "Ambient female" },
    { name = "a_f_y_hipster_02", label = "Hipster 02", category = "Ambient female" },
    { name = "a_f_y_hipster_03", label = "Hipster 03", category = "Ambient female" },
    { name = "a_f_y_hipster_04", label = "Hipster 04", category = "Ambient female" },
    { name = "a_f_y_indian_01", label = "Indian 01", category = "Ambient female" },
    { name = "a_f_y_juggalo_01", label = "Juggalo 01", category = "Ambient female" },
    { name = "a_f_y_runner_01", label = "Runner 01", category = "Ambient female" },
    { name = "a_f_y_rurmeth_01", label = "Rurmeth 01", category = "Ambient female" },
    { name = "a_f_y_scdressy_01", label = "Scdressy 01", category = "Ambient female" },
    { name = "a_f_y_skater_01", label = "Skater 01", category = "Ambient female" },
    { name = "a_f_y_soucent_01", label = "Soucent 01", category = "Ambient female" },
    { name = "a_f_y_soucent_02", label = "Soucent 02", category = "Ambient female" },
    { name = "a_f_y_soucent_03", label = "Soucent 03", category = "Ambient female" },
    { name = "a_f_y_tennis_01", label = "Tennis 01", category = "Ambient female" },
    { name = "a_f_y_topless_01", label = "Topless 01", category = "Ambient female" },
    { name = "a_f_y_tourist_01", label = "Tourist 01", category = "Ambient female" },
    { name = "a_f_y_tourist_02", label = "Tourist 02", category = "Ambient female" },
    { name = "a_f_y_vinewood_01", label = "Vinewood 01", category = "Ambient female" },
    { name = "a_f_y_vinewood_02", label = "Vinewood 02", category = "Ambient female" },
    { name = "a_f_y_vinewood_03", label = "Vinewood 03", category = "Ambient female" },
    { name = "a_f_y_vinewood_04", label = "Vinewood 04", category = "Ambient female" },
    { name = "a_f_y_yoga_01", label = "Yoga 01", category = "Ambient female" },
    { name = "a_f_y_gencaspat_01", label = "Gencaspat 01", category = "Ambient female" },
    { name = "a_f_y_smartcaspat_01", label = "Smartcaspat 01", category = "Ambient female" },

    -- Ambient male (129)
    { name = "a_m_m_acult_01", label = "Acult 01", category = "Ambient male" },
    { name = "a_m_m_afriamer_01", label = "Afriamer 01", category = "Ambient male" },
    { name = "a_m_m_beach_01", label = "Beach 01", category = "Ambient male" },
    { name = "a_m_m_beach_02", label = "Beach 02", category = "Ambient male" },
    { name = "a_m_m_bevhills_01", label = "Bevhills 01", category = "Ambient male" },
    { name = "a_m_m_bevhills_02", label = "Bevhills 02", category = "Ambient male" },
    { name = "a_m_m_business_01", label = "Business 01", category = "Ambient male" },
    { name = "a_m_m_eastsa_01", label = "Eastsa 01", category = "Ambient male" },
    { name = "a_m_m_eastsa_02", label = "Eastsa 02", category = "Ambient male" },
    { name = "a_m_m_farmer_01", label = "Farmer 01", category = "Ambient male" },
    { name = "a_m_m_fatlatin_01", label = "Fatlatin 01", category = "Ambient male" },
    { name = "a_m_m_genfat_01", label = "Genfat 01", category = "Ambient male" },
    { name = "a_m_m_genfat_02", label = "Genfat 02", category = "Ambient male" },
    { name = "a_m_m_golfer_01", label = "Golfer 01", category = "Ambient male" },
    { name = "a_m_m_hasjew_01", label = "Hasjew 01", category = "Ambient male" },
    { name = "a_m_m_hillbilly_01", label = "Hillbilly 01", category = "Ambient male" },
    { name = "a_m_m_hillbilly_02", label = "Hillbilly 02", category = "Ambient male" },
    { name = "a_m_m_indian_01", label = "Indian 01", category = "Ambient male" },
    { name = "a_m_m_ktown_01", label = "Ktown 01", category = "Ambient male" },
    { name = "a_m_m_malibu_01", label = "Malibu 01", category = "Ambient male" },
    { name = "a_m_m_mexcntry_01", label = "Mexcntry 01", category = "Ambient male" },
    { name = "a_m_m_mexlabor_01", label = "Mexlabor 01", category = "Ambient male" },
    { name = "a_m_m_og_boss_01", label = "Og Boss 01", category = "Ambient male" },
    { name = "a_m_m_paparazzi_01", label = "Paparazzi 01", category = "Ambient male" },
    { name = "a_m_m_polynesian_01", label = "Polynesian 01", category = "Ambient male" },
    { name = "a_m_m_prolhost_01", label = "Prolhost 01", category = "Ambient male" },
    { name = "a_m_m_rurmeth_01", label = "Rurmeth 01", category = "Ambient male" },
    { name = "a_m_m_salton_01", label = "Salton 01", category = "Ambient male" },
    { name = "a_m_m_salton_02", label = "Salton 02", category = "Ambient male" },
    { name = "a_m_m_salton_03", label = "Salton 03", category = "Ambient male" },
    { name = "a_m_m_salton_04", label = "Salton 04", category = "Ambient male" },
    { name = "a_m_m_skater_01", label = "Skater 01", category = "Ambient male" },
    { name = "a_m_m_skidrow_01", label = "Skidrow 01", category = "Ambient male" },
    { name = "a_m_m_socenlat_01", label = "Socenlat 01", category = "Ambient male" },
    { name = "a_m_m_soucent_01", label = "Soucent 01", category = "Ambient male" },
    { name = "a_m_m_soucent_02", label = "Soucent 02", category = "Ambient male" },
    { name = "a_m_m_soucent_03", label = "Soucent 03", category = "Ambient male" },
    { name = "a_m_m_soucent_04", label = "Soucent 04", category = "Ambient male" },
    { name = "a_m_m_stlat_02", label = "Stlat 02", category = "Ambient male" },
    { name = "a_m_m_tennis_01", label = "Tennis 01", category = "Ambient male" },
    { name = "a_m_m_tourist_01", label = "Tourist 01", category = "Ambient male" },
    { name = "a_m_m_tramp_01", label = "Tramp 01", category = "Ambient male" },
    { name = "a_m_m_trampbeac_01", label = "Trampbeac 01", category = "Ambient male" },
    { name = "a_m_m_tranvest_01", label = "Tranvest 01", category = "Ambient male" },
    { name = "a_m_m_tranvest_02", label = "Tranvest 02", category = "Ambient male" },
    { name = "a_m_o_acult_01", label = "Acult 01", category = "Ambient male" },
    { name = "a_m_o_acult_02", label = "Acult 02", category = "Ambient male" },
    { name = "a_m_o_beach_01", label = "Beach 01", category = "Ambient male" },
    { name = "a_m_o_genstreet_01", label = "Genstreet 01", category = "Ambient male" },
    { name = "a_m_o_ktown_01", label = "Ktown 01", category = "Ambient male" },
    { name = "a_m_o_salton_01", label = "Salton 01", category = "Ambient male" },
    { name = "a_m_o_soucent_01", label = "Soucent 01", category = "Ambient male" },
    { name = "a_m_o_soucent_02", label = "Soucent 02", category = "Ambient male" },
    { name = "a_m_o_soucent_03", label = "Soucent 03", category = "Ambient male" },
    { name = "a_m_o_tramp_01", label = "Tramp 01", category = "Ambient male" },
    { name = "a_m_y_acult_01", label = "Acult 01", category = "Ambient male" },
    { name = "a_m_y_acult_02", label = "Acult 02", category = "Ambient male" },
    { name = "a_m_y_beach_01", label = "Beach 01", category = "Ambient male" },
    { name = "a_m_y_beach_02", label = "Beach 02", category = "Ambient male" },
    { name = "a_m_y_beach_03", label = "Beach 03", category = "Ambient male" },
    { name = "a_m_y_beachvesp_01", label = "Beachvesp 01", category = "Ambient male" },
    { name = "a_m_y_beachvesp_02", label = "Beachvesp 02", category = "Ambient male" },
    { name = "a_m_y_bevhills_01", label = "Bevhills 01", category = "Ambient male" },
    { name = "a_m_y_bevhills_02", label = "Bevhills 02", category = "Ambient male" },
    { name = "a_m_y_breakdance_01", label = "Breakdance 01", category = "Ambient male" },
    { name = "a_m_y_busicas_01", label = "Busicas 01", category = "Ambient male" },
    { name = "a_m_y_business_01", label = "Business 01", category = "Ambient male" },
    { name = "a_m_y_business_02", label = "Business 02", category = "Ambient male" },
    { name = "a_m_y_business_03", label = "Business 03", category = "Ambient male" },
    { name = "a_m_y_clubcust_01", label = "Clubcust 01", category = "Ambient male" },
    { name = "a_m_y_clubcust_02", label = "Clubcust 02", category = "Ambient male" },
    { name = "a_m_y_clubcust_03", label = "Clubcust 03", category = "Ambient male" },
    { name = "a_m_y_cyclist_01", label = "Cyclist 01", category = "Ambient male" },
    { name = "a_m_y_dhill_01", label = "Dhill 01", category = "Ambient male" },
    { name = "a_m_y_downtown_01", label = "Downtown 01", category = "Ambient male" },
    { name = "a_m_y_eastsa_01", label = "Eastsa 01", category = "Ambient male" },
    { name = "a_m_y_eastsa_02", label = "Eastsa 02", category = "Ambient male" },
    { name = "a_m_y_epsilon_01", label = "Epsilon 01", category = "Ambient male" },
    { name = "a_m_y_epsilon_02", label = "Epsilon 02", category = "Ambient male" },
    { name = "a_m_y_gay_01", label = "Gay 01", category = "Ambient male" },
    { name = "a_m_y_gay_02", label = "Gay 02", category = "Ambient male" },
    { name = "a_m_y_genstreet_01", label = "Genstreet 01", category = "Ambient male" },
    { name = "a_m_y_genstreet_02", label = "Genstreet 02", category = "Ambient male" },
    { name = "a_m_y_golfer_01", label = "Golfer 01", category = "Ambient male" },
    { name = "a_m_y_hasjew_01", label = "Hasjew 01", category = "Ambient male" },
    { name = "a_m_y_hiker_01", label = "Hiker 01", category = "Ambient male" },
    { name = "a_m_y_hippy_01", label = "Hippy 01", category = "Ambient male" },
    { name = "a_m_y_hipster_01", label = "Hipster 01", category = "Ambient male" },
    { name = "a_m_y_hipster_02", label = "Hipster 02", category = "Ambient male" },
    { name = "a_m_y_hipster_03", label = "Hipster 03", category = "Ambient male" },
    { name = "a_m_y_indian_01", label = "Indian 01", category = "Ambient male" },
    { name = "a_m_y_jetski_01", label = "Jetski 01", category = "Ambient male" },
    { name = "a_m_y_juggalo_01", label = "Juggalo 01", category = "Ambient male" },
    { name = "a_m_y_ktown_01", label = "Ktown 01", category = "Ambient male" },
    { name = "a_m_y_ktown_02", label = "Ktown 02", category = "Ambient male" },
    { name = "a_m_y_latino_01", label = "Latino 01", category = "Ambient male" },
    { name = "a_m_y_methhead_01", label = "Methhead 01", category = "Ambient male" },
    { name = "a_m_y_mexthug_01", label = "Mexthug 01", category = "Ambient male" },
    { name = "a_m_y_motox_01", label = "Motox 01", category = "Ambient male" },
    { name = "a_m_y_motox_02", label = "Motox 02", category = "Ambient male" },
    { name = "a_m_y_musclbeac_01", label = "Musclbeac 01", category = "Ambient male" },
    { name = "a_m_y_musclbeac_02", label = "Musclbeac 02", category = "Ambient male" },
    { name = "a_m_y_polynesian_01", label = "Polynesian 01", category = "Ambient male" },
    { name = "a_m_y_roadcyc_01", label = "Roadcyc 01", category = "Ambient male" },
    { name = "a_m_y_runner_01", label = "Runner 01", category = "Ambient male" },
    { name = "a_m_y_runner_02", label = "Runner 02", category = "Ambient male" },
    { name = "a_m_y_salton_01", label = "Salton 01", category = "Ambient male" },
    { name = "a_m_y_skater_01", label = "Skater 01", category = "Ambient male" },
    { name = "a_m_y_skater_02", label = "Skater 02", category = "Ambient male" },
    { name = "a_m_y_soucent_01", label = "Soucent 01", category = "Ambient male" },
    { name = "a_m_y_soucent_02", label = "Soucent 02", category = "Ambient male" },
    { name = "a_m_y_soucent_03", label = "Soucent 03", category = "Ambient male" },
    { name = "a_m_y_soucent_04", label = "Soucent 04", category = "Ambient male" },
    { name = "a_m_y_stbla_01", label = "Stbla 01", category = "Ambient male" },
    { name = "a_m_y_stbla_02", label = "Stbla 02", category = "Ambient male" },
    { name = "a_m_y_stlat_01", label = "Stlat 01", category = "Ambient male" },
    { name = "a_m_y_stwhi_01", label = "Stwhi 01", category = "Ambient male" },
    { name = "a_m_y_stwhi_02", label = "Stwhi 02", category = "Ambient male" },
    { name = "a_m_y_sunbathe_01", label = "Sunbathe 01", category = "Ambient male" },
    { name = "a_m_y_surfer_01", label = "Surfer 01", category = "Ambient male" },
    { name = "a_m_y_vindouche_01", label = "Vindouche 01", category = "Ambient male" },
    { name = "a_m_y_vinewood_01", label = "Vinewood 01", category = "Ambient male" },
    { name = "a_m_y_vinewood_02", label = "Vinewood 02", category = "Ambient male" },
    { name = "a_m_y_vinewood_03", label = "Vinewood 03", category = "Ambient male" },
    { name = "a_m_y_vinewood_04", label = "Vinewood 04", category = "Ambient male" },
    { name = "a_m_y_yoga_01", label = "Yoga 01", category = "Ambient male" },
    { name = "a_m_m_mlcrisis_01", label = "Mlcrisis 01", category = "Ambient male" },
    { name = "a_m_y_gencaspat_01", label = "Gencaspat 01", category = "Ambient male" },
    { name = "a_m_y_smartcaspat_01", label = "Smartcaspat 01", category = "Ambient male" },

    -- Gang female (6)
    { name = "g_f_importexport_01", label = "Importexport 01", category = "Gang female" },
    { name = "g_f_y_ballas_01", label = "Ballas 01", category = "Gang female" },
    { name = "g_f_y_families_01", label = "Families 01", category = "Gang female" },
    { name = "g_f_y_lost_01", label = "Lost 01", category = "Gang female" },
    { name = "g_f_y_vagos_01", label = "Vagos 01", category = "Gang female" },
    { name = "g_f_m_undeadmage", label = "Undeadmage", category = "Gang female" },

    -- Gang male (41)
    { name = "g_m_importexport_01", label = "Importexport 01", category = "Gang male" },
    { name = "g_m_m_armboss_01", label = "Armboss 01", category = "Gang male" },
    { name = "g_m_m_armgoon_01", label = "Armgoon 01", category = "Gang male" },
    { name = "g_m_m_armlieut_01", label = "Armlieut 01", category = "Gang male" },
    { name = "g_m_m_chemwork_01", label = "Chemwork 01", category = "Gang male" },
    { name = "g_m_m_chiboss_01", label = "Chiboss 01", category = "Gang male" },
    { name = "g_m_m_chicold_01", label = "Chicold 01", category = "Gang male" },
    { name = "g_m_m_chigoon_01", label = "Chigoon 01", category = "Gang male" },
    { name = "g_m_m_chigoon_02", label = "Chigoon 02", category = "Gang male" },
    { name = "g_m_m_korboss_01", label = "Korboss 01", category = "Gang male" },
    { name = "g_m_m_mexboss_01", label = "Mexboss 01", category = "Gang male" },
    { name = "g_m_m_mexboss_02", label = "Mexboss 02", category = "Gang male" },
    { name = "g_m_y_armgoon_02", label = "Armgoon 02", category = "Gang male" },
    { name = "g_m_y_azteca_01", label = "Azteca 01", category = "Gang male" },
    { name = "g_m_y_ballaeast_01", label = "Ballaeast 01", category = "Gang male" },
    { name = "g_m_y_ballaorig_01", label = "Ballaorig 01", category = "Gang male" },
    { name = "g_m_y_ballasout_01", label = "Ballasout 01", category = "Gang male" },
    { name = "g_m_y_famca_01", label = "Famca 01", category = "Gang male" },
    { name = "g_m_y_famdnf_01", label = "Famdnf 01", category = "Gang male" },
    { name = "g_m_y_famfor_01", label = "Famfor 01", category = "Gang male" },
    { name = "g_m_y_korean_01", label = "Korean 01", category = "Gang male" },
    { name = "g_m_y_korean_02", label = "Korean 02", category = "Gang male" },
    { name = "g_m_y_korlieut_01", label = "Korlieut 01", category = "Gang male" },
    { name = "g_m_y_lost_01", label = "Lost 01", category = "Gang male" },
    { name = "g_m_y_lost_02", label = "Lost 02", category = "Gang male" },
    { name = "g_m_y_lost_03", label = "Lost 03", category = "Gang male" },
    { name = "g_m_y_mexgang_01", label = "Mexgang 01", category = "Gang male" },
    { name = "g_m_y_mexgoon_01", label = "Mexgoon 01", category = "Gang male" },
    { name = "g_m_y_mexgoon_02", label = "Mexgoon 02", category = "Gang male" },
    { name = "g_m_y_mexgoon_03", label = "Mexgoon 03", category = "Gang male" },
    { name = "g_m_y_pologoon_01", label = "Pologoon 01", category = "Gang male" },
    { name = "g_m_y_pologoon_02", label = "Pologoon 02", category = "Gang male" },
    { name = "g_m_y_salvaboss_01", label = "Salvaboss 01", category = "Gang male" },
    { name = "g_m_y_salvagoon_01", label = "Salvagoon 01", category = "Gang male" },
    { name = "g_m_y_salvagoon_02", label = "Salvagoon 02", category = "Gang male" },
    { name = "g_m_y_salvagoon_03", label = "Salvagoon 03", category = "Gang male" },
    { name = "g_m_y_strpunk_01", label = "Strpunk 01", category = "Gang male" },
    { name = "g_m_y_strpunk_02", label = "Strpunk 02", category = "Gang male" },
    { name = "g_m_m_casrn_01", label = "Casrn 01", category = "Gang male" },
    { name = "g_m_m_zombie_04", label = "Zombie 04", category = "Gang male" },
    { name = "g_m_m_zombie_05", label = "Zombie 05", category = "Gang male" },

    -- Multiplayer (40)
    { name = "mp_f_bennymech_01", label = "Bennymech 01", category = "Multiplayer" },
    { name = "mp_f_boatstaff_01", label = "Boatstaff 01", category = "Multiplayer" },
    { name = "mp_f_cardesign_01", label = "Cardesign 01", category = "Multiplayer" },
    { name = "mp_f_chbar_01", label = "Chbar 01", category = "Multiplayer" },
    { name = "mp_f_cocaine_01", label = "Cocaine 01", category = "Multiplayer" },
    { name = "mp_f_counterfeit_01", label = "Counterfeit 01", category = "Multiplayer" },
    { name = "mp_f_deadhooker", label = "Deadhooker", category = "Multiplayer" },
    { name = "mp_f_execpa_01", label = "Execpa 01", category = "Multiplayer" },
    { name = "mp_f_execpa_02", label = "Execpa 02", category = "Multiplayer" },
    { name = "mp_f_forgery_01", label = "Forgery 01", category = "Multiplayer" },
    { name = "mp_f_freemode_01", label = "Freemode 01", category = "Multiplayer" },
    { name = "mp_f_helistaff_01", label = "Helistaff 01", category = "Multiplayer" },
    { name = "mp_f_meth_01", label = "Meth 01", category = "Multiplayer" },
    { name = "mp_f_misty_01", label = "Misty 01", category = "Multiplayer" },
    { name = "mp_f_stripperlite", label = "Stripperlite", category = "Multiplayer" },
    { name = "mp_f_weed_01", label = "Weed 01", category = "Multiplayer" },
    { name = "mp_g_m_pros_01", label = "Pros 01", category = "Multiplayer" },
    { name = "mp_m_avongoon", label = "Avongoon", category = "Multiplayer" },
    { name = "mp_m_boatstaff_01", label = "Boatstaff 01", category = "Multiplayer" },
    { name = "mp_m_bogdangoon", label = "Bogdangoon", category = "Multiplayer" },
    { name = "mp_m_claude_01", label = "Claude 01", category = "Multiplayer" },
    { name = "mp_m_cocaine_01", label = "Cocaine 01", category = "Multiplayer" },
    { name = "mp_m_counterfeit_01", label = "Counterfeit 01", category = "Multiplayer" },
    { name = "mp_m_exarmy_01", label = "Exarmy 01", category = "Multiplayer" },
    { name = "mp_m_execpa_01", label = "Execpa 01", category = "Multiplayer" },
    { name = "mp_m_famdd_01", label = "Famdd 01", category = "Multiplayer" },
    { name = "mp_m_fibsec_01", label = "Fibsec 01", category = "Multiplayer" },
    { name = "mp_m_forgery_01", label = "Forgery 01", category = "Multiplayer" },
    { name = "mp_m_freemode_01", label = "Freemode 01", category = "Multiplayer" },
    { name = "mp_m_g_vagfun_01", label = "G Vagfun 01", category = "Multiplayer" },
    { name = "mp_m_marston_01", label = "Marston 01", category = "Multiplayer" },
    { name = "mp_m_meth_01", label = "Meth 01", category = "Multiplayer" },
    { name = "mp_m_niko_01", label = "Niko 01", category = "Multiplayer" },
    { name = "mp_m_securoguard_01", label = "Securoguard 01", category = "Multiplayer" },
    { name = "mp_m_shopkeep_01", label = "Shopkeep 01", category = "Multiplayer" },
    { name = "mp_m_waremech_01", label = "Waremech 01", category = "Multiplayer" },
    { name = "mp_m_weapexp_01", label = "Weapexp 01", category = "Multiplayer" },
    { name = "mp_m_weapwork_01", label = "Weapwork 01", category = "Multiplayer" },
    { name = "mp_m_weed_01", label = "Weed 01", category = "Multiplayer" },
    { name = "mp_s_m_armoured_01", label = "Armoured 01", category = "Multiplayer" },

    -- Scenario female (25)
    { name = "s_f_m_fembarber", label = "Fembarber", category = "Scenario female" },
    { name = "s_f_m_maid_01", label = "Maid 01", category = "Scenario female" },
    { name = "s_f_m_shop_high", label = "Shop High", category = "Scenario female" },
    { name = "s_f_m_sweatshop_01", label = "Sweatshop 01", category = "Scenario female" },
    { name = "s_f_y_airhostess_01", label = "Airhostess 01", category = "Scenario female" },
    { name = "s_f_y_bartender_01", label = "Bartender 01", category = "Scenario female" },
    { name = "s_f_y_baywatch_01", label = "Baywatch 01", category = "Scenario female" },
    { name = "s_f_y_clubbar_01", label = "Clubbar 01", category = "Scenario female" },
    { name = "s_f_y_cop_01", label = "Cop 01", category = "Scenario female" },
    { name = "s_f_y_factory_01", label = "Factory 01", category = "Scenario female" },
    { name = "s_f_y_hooker_01", label = "Hooker 01", category = "Scenario female" },
    { name = "s_f_y_hooker_02", label = "Hooker 02", category = "Scenario female" },
    { name = "s_f_y_hooker_03", label = "Hooker 03", category = "Scenario female" },
    { name = "s_f_y_migrant_01", label = "Migrant 01", category = "Scenario female" },
    { name = "s_f_y_movprem_01", label = "Movprem 01", category = "Scenario female" },
    { name = "s_f_y_ranger_01", label = "Ranger 01", category = "Scenario female" },
    { name = "s_f_y_scrubs_01", label = "Scrubs 01", category = "Scenario female" },
    { name = "s_f_y_sheriff_01", label = "Sheriff 01", category = "Scenario female" },
    { name = "s_f_y_shop_low", label = "Shop Low", category = "Scenario female" },
    { name = "s_f_y_shop_mid", label = "Shop Mid", category = "Scenario female" },
    { name = "s_f_y_stripper_01", label = "Stripper 01", category = "Scenario female" },
    { name = "s_f_y_stripper_02", label = "Stripper 02", category = "Scenario female" },
    { name = "s_f_y_stripperlite", label = "Stripperlite", category = "Scenario female" },
    { name = "s_f_y_sweatshop_01", label = "Sweatshop 01", category = "Scenario female" },
    { name = "s_f_y_casino_01", label = "Casino 01", category = "Scenario female" },

    -- Scenario male (99)
    { name = "s_m_m_ammucountry", label = "Ammucountry", category = "Scenario male" },
    { name = "s_m_m_armoured_01", label = "Armoured 01", category = "Scenario male" },
    { name = "s_m_m_armoured_02", label = "Armoured 02", category = "Scenario male" },
    { name = "s_m_m_autoshop_01", label = "Autoshop 01", category = "Scenario male" },
    { name = "s_m_m_autoshop_02", label = "Autoshop 02", category = "Scenario male" },
    { name = "s_m_m_bouncer_01", label = "Bouncer 01", category = "Scenario male" },
    { name = "s_m_m_ccrew_01", label = "Ccrew 01", category = "Scenario male" },
    { name = "s_m_m_chemsec_01", label = "Chemsec 01", category = "Scenario male" },
    { name = "s_m_m_ciasec_01", label = "Ciasec 01", category = "Scenario male" },
    { name = "s_m_m_cntrybar_01", label = "Cntrybar 01", category = "Scenario male" },
    { name = "s_m_m_dockwork_01", label = "Dockwork 01", category = "Scenario male" },
    { name = "s_m_m_doctor_01", label = "Doctor 01", category = "Scenario male" },
    { name = "s_m_m_fiboffice_01", label = "Fiboffice 01", category = "Scenario male" },
    { name = "s_m_m_fiboffice_02", label = "Fiboffice 02", category = "Scenario male" },
    { name = "s_m_m_fibsec_01", label = "Fibsec 01", category = "Scenario male" },
    { name = "s_m_m_gaffer_01", label = "Gaffer 01", category = "Scenario male" },
    { name = "s_m_m_gardener_01", label = "Gardener 01", category = "Scenario male" },
    { name = "s_m_m_gentransport", label = "Gentransport", category = "Scenario male" },
    { name = "s_m_m_hairdress_01", label = "Hairdress 01", category = "Scenario male" },
    { name = "s_m_m_highsec_01", label = "Highsec 01", category = "Scenario male" },
    { name = "s_m_m_highsec_02", label = "Highsec 02", category = "Scenario male" },
    { name = "s_m_m_janitor", label = "Janitor", category = "Scenario male" },
    { name = "s_m_m_lathandy_01", label = "Lathandy 01", category = "Scenario male" },
    { name = "s_m_m_lifeinvad_01", label = "Lifeinvad 01", category = "Scenario male" },
    { name = "s_m_m_linecook", label = "Linecook", category = "Scenario male" },
    { name = "s_m_m_lsmetro_01", label = "Lsmetro 01", category = "Scenario male" },
    { name = "s_m_m_mariachi_01", label = "Mariachi 01", category = "Scenario male" },
    { name = "s_m_m_marine_01", label = "Marine 01", category = "Scenario male" },
    { name = "s_m_m_marine_02", label = "Marine 02", category = "Scenario male" },
    { name = "s_m_m_migrant_01", label = "Migrant 01", category = "Scenario male" },
    { name = "s_m_m_movalien_01", label = "Movalien 01", category = "Scenario male" },
    { name = "s_m_m_movprem_01", label = "Movprem 01", category = "Scenario male" },
    { name = "s_m_m_movspace_01", label = "Movspace 01", category = "Scenario male" },
    { name = "s_m_m_paramedic_01", label = "Paramedic 01", category = "Scenario male" },
    { name = "s_m_m_pilot_01", label = "Pilot 01", category = "Scenario male" },
    { name = "s_m_m_pilot_02", label = "Pilot 02", category = "Scenario male" },
    { name = "s_m_m_postal_01", label = "Postal 01", category = "Scenario male" },
    { name = "s_m_m_postal_02", label = "Postal 02", category = "Scenario male" },
    { name = "s_m_m_prisguard_01", label = "Prisguard 01", category = "Scenario male" },
    { name = "s_m_m_scientist_01", label = "Scientist 01", category = "Scenario male" },
    { name = "s_m_m_security_01", label = "Security 01", category = "Scenario male" },
    { name = "s_m_m_snowcop_01", label = "Snowcop 01", category = "Scenario male" },
    { name = "s_m_m_strperf_01", label = "Strperf 01", category = "Scenario male" },
    { name = "s_m_m_strpreach_01", label = "Strpreach 01", category = "Scenario male" },
    { name = "s_m_m_strvend_01", label = "Strvend 01", category = "Scenario male" },
    { name = "s_m_m_trucker_01", label = "Trucker 01", category = "Scenario male" },
    { name = "s_m_m_ups_01", label = "Ups 01", category = "Scenario male" },
    { name = "s_m_m_ups_02", label = "Ups 02", category = "Scenario male" },
    { name = "s_m_o_busker_01", label = "Busker 01", category = "Scenario male" },
    { name = "s_m_y_airworker", label = "Airworker", category = "Scenario male" },
    { name = "s_m_y_ammucity_01", label = "Ammucity 01", category = "Scenario male" },
    { name = "s_m_y_armymech_01", label = "Armymech 01", category = "Scenario male" },
    { name = "s_m_y_autopsy_01", label = "Autopsy 01", category = "Scenario male" },
    { name = "s_m_y_barman_01", label = "Barman 01", category = "Scenario male" },
    { name = "s_m_y_baywatch_01", label = "Baywatch 01", category = "Scenario male" },
    { name = "s_m_y_blackops_01", label = "Blackops 01", category = "Scenario male" },
    { name = "s_m_y_blackops_02", label = "Blackops 02", category = "Scenario male" },
    { name = "s_m_y_blackops_03", label = "Blackops 03", category = "Scenario male" },
    { name = "s_m_y_busboy_01", label = "Busboy 01", category = "Scenario male" },
    { name = "s_m_y_chef_01", label = "Chef 01", category = "Scenario male" },
    { name = "s_m_y_clown_01", label = "Clown 01", category = "Scenario male" },
    { name = "s_m_y_clubbar_01", label = "Clubbar 01", category = "Scenario male" },
    { name = "s_m_y_construct_01", label = "Construct 01", category = "Scenario male" },
    { name = "s_m_y_construct_02", label = "Construct 02", category = "Scenario male" },
    { name = "s_m_y_cop_01", label = "Cop 01", category = "Scenario male" },
    { name = "s_m_y_dealer_01", label = "Dealer 01", category = "Scenario male" },
    { name = "s_m_y_devinsec_01", label = "Devinsec 01", category = "Scenario male" },
    { name = "s_m_y_dockwork_01", label = "Dockwork 01", category = "Scenario male" },
    { name = "s_m_y_doorman_01", label = "Doorman 01", category = "Scenario male" },
    { name = "s_m_y_dwservice_01", label = "Dwservice 01", category = "Scenario male" },
    { name = "s_m_y_dwservice_02", label = "Dwservice 02", category = "Scenario male" },
    { name = "s_m_y_factory_01", label = "Factory 01", category = "Scenario male" },
    { name = "s_m_y_fireman_01", label = "Fireman 01", category = "Scenario male" },
    { name = "s_m_y_garbage", label = "Garbage", category = "Scenario male" },
    { name = "s_m_y_grip_01", label = "Grip 01", category = "Scenario male" },
    { name = "s_m_y_hwaycop_01", label = "Hwaycop 01", category = "Scenario male" },
    { name = "s_m_y_marine_01", label = "Marine 01", category = "Scenario male" },
    { name = "s_m_y_marine_02", label = "Marine 02", category = "Scenario male" },
    { name = "s_m_y_marine_03", label = "Marine 03", category = "Scenario male" },
    { name = "s_m_y_mime", label = "Mime", category = "Scenario male" },
    { name = "s_m_y_pestcont_01", label = "Pestcont 01", category = "Scenario male" },
    { name = "s_m_y_pilot_01", label = "Pilot 01", category = "Scenario male" },
    { name = "s_m_y_prismuscl_01", label = "Prismuscl 01", category = "Scenario male" },
    { name = "s_m_y_prisoner_01", label = "Prisoner 01", category = "Scenario male" },
    { name = "s_m_y_ranger_01", label = "Ranger 01", category = "Scenario male" },
    { name = "s_m_y_robber_01", label = "Robber 01", category = "Scenario male" },
    { name = "s_m_y_sheriff_01", label = "Sheriff 01", category = "Scenario male" },
    { name = "s_m_y_shop_mask", label = "Shop Mask", category = "Scenario male" },
    { name = "s_m_y_strvend_01", label = "Strvend 01", category = "Scenario male" },
    { name = "s_m_y_swat_01", label = "Swat 01", category = "Scenario male" },
    { name = "s_m_y_uscg_01", label = "Uscg 01", category = "Scenario male" },
    { name = "s_m_y_valet_01", label = "Valet 01", category = "Scenario male" },
    { name = "s_m_y_waiter_01", label = "Waiter 01", category = "Scenario male" },
    { name = "s_m_y_waretech_01", label = "Waretech 01", category = "Scenario male" },
    { name = "s_m_y_winclean_01", label = "Winclean 01", category = "Scenario male" },
    { name = "s_m_y_xmech_01", label = "Xmech 01", category = "Scenario male" },
    { name = "s_m_y_xmech_02", label = "Xmech 02", category = "Scenario male" },
    { name = "s_m_y_casino_01", label = "Casino 01", category = "Scenario male" },
    { name = "s_m_y_westsec_01", label = "Westsec 01", category = "Scenario male" },

    -- Story scenario female (28)
    { name = "u_f_m_corpse_01", label = "Corpse 01", category = "Story scenario female" },
    { name = "u_f_m_miranda", label = "Miranda", category = "Story scenario female" },
    { name = "u_f_m_miranda_02", label = "Miranda 02", category = "Story scenario female" },
    { name = "u_f_m_promourn_01", label = "Promourn 01", category = "Story scenario female" },
    { name = "u_f_o_moviestar", label = "Moviestar", category = "Story scenario female" },
    { name = "u_f_o_prolhost_01", label = "Prolhost 01", category = "Story scenario female" },
    { name = "u_f_y_bikerchic", label = "Bikerchic", category = "Story scenario female" },
    { name = "u_f_y_comjane", label = "Comjane", category = "Story scenario female" },
    { name = "u_f_y_corpse_01", label = "Corpse 01", category = "Story scenario female" },
    { name = "u_f_y_corpse_02", label = "Corpse 02", category = "Story scenario female" },
    { name = "u_f_y_danceburl_01", label = "Danceburl 01", category = "Story scenario female" },
    { name = "u_f_y_dancelthr_01", label = "Dancelthr 01", category = "Story scenario female" },
    { name = "u_f_y_dancerave_01", label = "Dancerave 01", category = "Story scenario female" },
    { name = "u_f_y_hotposh_01", label = "Hotposh 01", category = "Story scenario female" },
    { name = "u_f_y_jewelass_01", label = "Jewelass 01", category = "Story scenario female" },
    { name = "u_f_y_mistress", label = "Mistress", category = "Story scenario female" },
    { name = "u_f_y_poppymich", label = "Poppymich", category = "Story scenario female" },
    { name = "u_f_y_poppymich_02", label = "Poppymich 02", category = "Story scenario female" },
    { name = "u_f_y_princess", label = "Princess", category = "Story scenario female" },
    { name = "u_f_y_spyactress", label = "Spyactress", category = "Story scenario female" },
    { name = "u_f_m_casinocash_01", label = "Casinocash 01", category = "Story scenario female" },
    { name = "u_f_m_casinoshop_01", label = "Casinoshop 01", category = "Story scenario female" },
    { name = "u_f_m_debbie_01", label = "Debbie 01", category = "Story scenario female" },
    { name = "u_f_o_carol", label = "Carol", category = "Story scenario female" },
    { name = "u_f_o_eileen", label = "Eileen", category = "Story scenario female" },
    { name = "u_f_y_beth", label = "Beth", category = "Story scenario female" },
    { name = "u_f_y_lauren", label = "Lauren", category = "Story scenario female" },
    { name = "u_f_y_taylor", label = "Taylor", category = "Story scenario female" },

    -- Story scenario male (63)
    { name = "u_m_m_aldinapoli", label = "Aldinapoli", category = "Story scenario male" },
    { name = "u_m_m_bankman", label = "Bankman", category = "Story scenario male" },
    { name = "u_m_m_bikehire_01", label = "Bikehire 01", category = "Story scenario male" },
    { name = "u_m_m_doa_01", label = "Doa 01", category = "Story scenario male" },
    { name = "u_m_m_edtoh", label = "Edtoh", category = "Story scenario male" },
    { name = "u_m_m_fibarchitect", label = "Fibarchitect", category = "Story scenario male" },
    { name = "u_m_m_filmdirector", label = "Filmdirector", category = "Story scenario male" },
    { name = "u_m_m_glenstank_01", label = "Glenstank 01", category = "Story scenario male" },
    { name = "u_m_m_griff_01", label = "Griff 01", category = "Story scenario male" },
    { name = "u_m_m_jesus_01", label = "Jesus 01", category = "Story scenario male" },
    { name = "u_m_m_jewelsec_01", label = "Jewelsec 01", category = "Story scenario male" },
    { name = "u_m_m_jewelthief", label = "Jewelthief", category = "Story scenario male" },
    { name = "u_m_m_markfost", label = "Markfost", category = "Story scenario male" },
    { name = "u_m_m_partytarget", label = "Partytarget", category = "Story scenario male" },
    { name = "u_m_m_prolsec_01", label = "Prolsec 01", category = "Story scenario male" },
    { name = "u_m_m_promourn_01", label = "Promourn 01", category = "Story scenario male" },
    { name = "u_m_m_rivalpap", label = "Rivalpap", category = "Story scenario male" },
    { name = "u_m_m_spyactor", label = "Spyactor", category = "Story scenario male" },
    { name = "u_m_m_streetart_01", label = "Streetart 01", category = "Story scenario male" },
    { name = "u_m_m_willyfist", label = "Willyfist", category = "Story scenario male" },
    { name = "u_m_o_filmnoir", label = "Filmnoir", category = "Story scenario male" },
    { name = "u_m_o_finguru_01", label = "Finguru 01", category = "Story scenario male" },
    { name = "u_m_o_taphillbilly", label = "Taphillbilly", category = "Story scenario male" },
    { name = "u_m_o_tramp_01", label = "Tramp 01", category = "Story scenario male" },
    { name = "u_m_y_abner", label = "Abner", category = "Story scenario male" },
    { name = "u_m_y_antonb", label = "Antonb", category = "Story scenario male" },
    { name = "u_m_y_babyd", label = "Babyd", category = "Story scenario male" },
    { name = "u_m_y_baygor", label = "Baygor", category = "Story scenario male" },
    { name = "u_m_y_burgerdrug_01", label = "Burgerdrug 01", category = "Story scenario male" },
    { name = "u_m_y_chip", label = "Chip", category = "Story scenario male" },
    { name = "u_m_y_corpse_01", label = "Corpse 01", category = "Story scenario male" },
    { name = "u_m_y_cyclist_01", label = "Cyclist 01", category = "Story scenario male" },
    { name = "u_m_y_danceburl_01", label = "Danceburl 01", category = "Story scenario male" },
    { name = "u_m_y_dancelthr_01", label = "Dancelthr 01", category = "Story scenario male" },
    { name = "u_m_y_dancerave_01", label = "Dancerave 01", category = "Story scenario male" },
    { name = "u_m_y_fibmugger_01", label = "Fibmugger 01", category = "Story scenario male" },
    { name = "u_m_y_guido_01", label = "Guido 01", category = "Story scenario male" },
    { name = "u_m_y_gunvend_01", label = "Gunvend 01", category = "Story scenario male" },
    { name = "u_m_y_hippie_01", label = "Hippie 01", category = "Story scenario male" },
    { name = "u_m_y_imporage", label = "Imporage", category = "Story scenario male" },
    { name = "u_m_y_juggernaut_01", label = "Juggernaut 01", category = "Story scenario male" },
    { name = "u_m_y_justin", label = "Justin", category = "Story scenario male" },
    { name = "u_m_y_mani", label = "Mani", category = "Story scenario male" },
    { name = "u_m_y_militarybum", label = "Militarybum", category = "Story scenario male" },
    { name = "u_m_y_paparazzi", label = "Paparazzi", category = "Story scenario male" },
    { name = "u_m_y_party_01", label = "Party 01", category = "Story scenario male" },
    { name = "u_m_y_pogo_01", label = "Pogo 01", category = "Story scenario male" },
    { name = "u_m_y_prisoner_01", label = "Prisoner 01", category = "Story scenario male" },
    { name = "u_m_y_proldriver_01", label = "Proldriver 01", category = "Story scenario male" },
    { name = "u_m_y_rsranger_01", label = "Rsranger 01", category = "Story scenario male" },
    { name = "u_m_y_sbike", label = "Sbike", category = "Story scenario male" },
    { name = "u_m_y_smugmech_01", label = "Smugmech 01", category = "Story scenario male" },
    { name = "u_m_y_staggrm_01", label = "Staggrm 01", category = "Story scenario male" },
    { name = "u_m_y_tattoo_01", label = "Tattoo 01", category = "Story scenario male" },
    { name = "u_m_y_zombie_01", label = "Zombie 01", category = "Story scenario male" },
    { name = "u_m_m_blane", label = "Blane", category = "Story scenario male" },
    { name = "u_m_m_curtis", label = "Curtis", category = "Story scenario male" },
    { name = "u_m_m_vince", label = "Vince", category = "Story scenario male" },
    { name = "u_m_o_dean", label = "Dean", category = "Story scenario male" },
    { name = "u_m_y_caleb", label = "Caleb", category = "Story scenario male" },
    { name = "u_m_y_croupthief_01", label = "Croupthief 01", category = "Story scenario male" },
    { name = "u_m_y_gabriel", label = "Gabriel", category = "Story scenario male" },
    { name = "u_m_y_ushi", label = "Ushi", category = "Story scenario male" },

    -- Story (155)
    { name = "hc_driver", label = "Driver", category = "Story" },
    { name = "hc_gunman", label = "Gunman", category = "Story" },
    { name = "hc_hacker", label = "Hacker", category = "Story" },
    { name = "ig_abigail", label = "Abigail", category = "Story" },
    { name = "ig_agent", label = "Agent", category = "Story" },
    { name = "ig_agent14_02", label = "Agent14 02", category = "Story" },
    { name = "ig_amandatownley", label = "Amandatownley", category = "Story" },
    { name = "ig_andreas", label = "Andreas", category = "Story" },
    { name = "ig_ashley", label = "Ashley", category = "Story" },
    { name = "ig_avon", label = "Avon", category = "Story" },
    { name = "ig_ballasog", label = "Ballasog", category = "Story" },
    { name = "ig_bankman", label = "Bankman", category = "Story" },
    { name = "ig_barry", label = "Barry", category = "Story" },
    { name = "ig_benny", label = "Benny", category = "Story" },
    { name = "ig_bestmen", label = "Bestmen", category = "Story" },
    { name = "ig_beverly", label = "Beverly", category = "Story" },
    { name = "ig_brad", label = "Brad", category = "Story" },
    { name = "ig_bride", label = "Bride", category = "Story" },
    { name = "ig_car3guy1", label = "Car3guy1", category = "Story" },
    { name = "ig_car3guy2", label = "Car3guy2", category = "Story" },
    { name = "ig_casey", label = "Casey", category = "Story" },
    { name = "ig_chef", label = "Chef", category = "Story" },
    { name = "ig_chef2", label = "Chef2", category = "Story" },
    { name = "ig_chengsr", label = "Chengsr", category = "Story" },
    { name = "ig_chrisformage", label = "Chrisformage", category = "Story" },
    { name = "ig_clay", label = "Clay", category = "Story" },
    { name = "ig_claypain", label = "Claypain", category = "Story" },
    { name = "ig_cletus", label = "Cletus", category = "Story" },
    { name = "ig_dale", label = "Dale", category = "Story" },
    { name = "ig_davenorton", label = "Davenorton", category = "Story" },
    { name = "ig_denise", label = "Denise", category = "Story" },
    { name = "ig_devin", label = "Devin", category = "Story" },
    { name = "ig_dix", label = "Dix", category = "Story" },
    { name = "ig_djblamadon", label = "Djblamadon", category = "Story" },
    { name = "ig_djblamrupert", label = "Djblamrupert", category = "Story" },
    { name = "ig_djblamryans", label = "Djblamryans", category = "Story" },
    { name = "ig_djdixmanager", label = "Djdixmanager", category = "Story" },
    { name = "ig_djgeneric_01", label = "Djgeneric 01", category = "Story" },
    { name = "ig_djsolfotios", label = "Djsolfotios", category = "Story" },
    { name = "ig_djsoljakob", label = "Djsoljakob", category = "Story" },
    { name = "ig_djsolmanager", label = "Djsolmanager", category = "Story" },
    { name = "ig_djsolmike", label = "Djsolmike", category = "Story" },
    { name = "ig_djsolrobt", label = "Djsolrobt", category = "Story" },
    { name = "ig_djtalaurelia", label = "Djtalaurelia", category = "Story" },
    { name = "ig_djtalignazio", label = "Djtalignazio", category = "Story" },
    { name = "ig_dom", label = "Dom", category = "Story" },
    { name = "ig_dreyfuss", label = "Dreyfuss", category = "Story" },
    { name = "ig_drfriedlander", label = "Drfriedlander", category = "Story" },
    { name = "ig_englishdave", label = "Englishdave", category = "Story" },
    { name = "ig_fabien", label = "Fabien", category = "Story" },
    { name = "ig_fbisuit_01", label = "Fbisuit 01", category = "Story" },
    { name = "ig_floyd", label = "Floyd", category = "Story" },
    { name = "ig_g", label = "G", category = "Story" },
    { name = "ig_groom", label = "Groom", category = "Story" },
    { name = "ig_gustavo_02", label = "Gustavo 02", category = "Story" },
    { name = "ig_hao", label = "Hao", category = "Story" },
    { name = "ig_hunter", label = "Hunter", category = "Story" },
    { name = "ig_janet", label = "Janet", category = "Story" },
    { name = "ig_jay_norris", label = "Jay Norris", category = "Story" },
    { name = "ig_jewelass", label = "Jewelass", category = "Story" },
    { name = "ig_jimmyboston", label = "Jimmyboston", category = "Story" },
    { name = "ig_jimmyboston_02", label = "Jimmyboston 02", category = "Story" },
    { name = "ig_jimmydisanto", label = "Jimmydisanto", category = "Story" },
    { name = "ig_joeminuteman", label = "Joeminuteman", category = "Story" },
    { name = "ig_johnnyklebitz", label = "Johnnyklebitz", category = "Story" },
    { name = "ig_josef", label = "Josef", category = "Story" },
    { name = "ig_josh", label = "Josh", category = "Story" },
    { name = "ig_karen_daniels", label = "Karen Daniels", category = "Story" },
    { name = "ig_kerrymcintosh", label = "Kerrymcintosh", category = "Story" },
    { name = "ig_kerrymcintosh_02", label = "Kerrymcintosh 02", category = "Story" },
    { name = "ig_lacey_jones_02", label = "Lacey Jones 02", category = "Story" },
    { name = "ig_lamardavis", label = "Lamardavis", category = "Story" },
    { name = "ig_lazlow", label = "Lazlow", category = "Story" },
    { name = "ig_lazlow_2", label = "Lazlow 2", category = "Story" },
    { name = "ig_lestercrest", label = "Lestercrest", category = "Story" },
    { name = "ig_lestercrest_2", label = "Lestercrest 2", category = "Story" },
    { name = "ig_lifeinvad_01", label = "Lifeinvad 01", category = "Story" },
    { name = "ig_lifeinvad_02", label = "Lifeinvad 02", category = "Story" },
    { name = "ig_magenta", label = "Magenta", category = "Story" },
    { name = "ig_madrazodriver_01", label = "Madrazodriver 01", category = "Story" },
    { name = "ig_martinmadrazo_02", label = "Martinmadrazo 02", category = "Story" },
    { name = "ig_rafdeangelis", label = "Rafdeangelis", category = "Story" },
    { name = "ig_skeleton_01", label = "Skeleton 01", category = "Story" },
    { name = "ig_valentina", label = "Valentina", category = "Story" },
    { name = "ig_weiss", label = "Weiss", category = "Story" },
    { name = "ig_zombie_dj_01", label = "Zombie Dj 01", category = "Story" },
    { name = "ig_malc", label = "Malc", category = "Story" },
    { name = "ig_manuel", label = "Manuel", category = "Story" },
    { name = "ig_marnie", label = "Marnie", category = "Story" },
    { name = "ig_maryann", label = "Maryann", category = "Story" },
    { name = "ig_maude", label = "Maude", category = "Story" },
    { name = "ig_michelle", label = "Michelle", category = "Story" },
    { name = "ig_milton", label = "Milton", category = "Story" },
    { name = "ig_molly", label = "Molly", category = "Story" },
    { name = "ig_money", label = "Money", category = "Story" },
    { name = "ig_mp_agent14", label = "Mp Agent14", category = "Story" },
    { name = "ig_mrk", label = "Mrk", category = "Story" },
    { name = "ig_mrs_thornhill", label = "Mrs Thornhill", category = "Story" },
    { name = "ig_mrsphillips", label = "Mrsphillips", category = "Story" },
    { name = "ig_natalia", label = "Natalia", category = "Story" },
    { name = "ig_nervousron", label = "Nervousron", category = "Story" },
    { name = "ig_nigel", label = "Nigel", category = "Story" },
    { name = "ig_old_man1a", label = "Old Man1a", category = "Story" },
    { name = "ig_old_man2", label = "Old Man2", category = "Story" },
    { name = "ig_omega", label = "Omega", category = "Story" },
    { name = "ig_oneil", label = "Oneil", category = "Story" },
    { name = "ig_orleans", label = "Orleans", category = "Story" },
    { name = "ig_ortega", label = "Ortega", category = "Story" },
    { name = "ig_paige", label = "Paige", category = "Story" },
    { name = "ig_paper", label = "Paper", category = "Story" },
    { name = "ig_patricia", label = "Patricia", category = "Story" },
    { name = "ig_popov", label = "Popov", category = "Story" },
    { name = "ig_priest", label = "Priest", category = "Story" },
    { name = "ig_prolsec_02", label = "Prolsec 02", category = "Story" },
    { name = "ig_ramp_gang", label = "Ramp Gang", category = "Story" },
    { name = "ig_ramp_hic", label = "Ramp Hic", category = "Story" },
    { name = "ig_ramp_hipster", label = "Ramp Hipster", category = "Story" },
    { name = "ig_ramp_mex", label = "Ramp Mex", category = "Story" },
    { name = "ig_rashcosvki", label = "Rashcosvki", category = "Story" },
    { name = "ig_roccopelosi", label = "Roccopelosi", category = "Story" },
    { name = "ig_russiandrunk", label = "Russiandrunk", category = "Story" },
    { name = "ig_sacha", label = "Sacha", category = "Story" },
    { name = "ig_screen_writer", label = "Screen Writer", category = "Story" },
    { name = "ig_siemonyetarian", label = "Siemonyetarian", category = "Story" },
    { name = "ig_sol", label = "Sol", category = "Story" },
    { name = "ig_solomon", label = "Solomon", category = "Story" },
    { name = "ig_stevehains", label = "Stevehains", category = "Story" },
    { name = "ig_stretch", label = "Stretch", category = "Story" },
    { name = "ig_talcc", label = "Talcc", category = "Story" },
    { name = "ig_talina", label = "Talina", category = "Story" },
    { name = "ig_talmm", label = "Talmm", category = "Story" },
    { name = "ig_tanisha", label = "Tanisha", category = "Story" },
    { name = "ig_taocheng", label = "Taocheng", category = "Story" },
    { name = "ig_taostranslator", label = "Taostranslator", category = "Story" },
    { name = "ig_tenniscoach", label = "Tenniscoach", category = "Story" },
    { name = "ig_terry", label = "Terry", category = "Story" },
    { name = "ig_tomepsilon", label = "Tomepsilon", category = "Story" },
    { name = "ig_tonya", label = "Tonya", category = "Story" },
    { name = "ig_tonyprince", label = "Tonyprince", category = "Story" },
    { name = "ig_tracydisanto", label = "Tracydisanto", category = "Story" },
    { name = "ig_trafficwarden", label = "Trafficwarden", category = "Story" },
    { name = "ig_tylerdix", label = "Tylerdix", category = "Story" },
    { name = "ig_tylerdix_02", label = "Tylerdix 02", category = "Story" },
    { name = "ig_vagspeak", label = "Vagspeak", category = "Story" },
    { name = "ig_wade", label = "Wade", category = "Story" },
    { name = "ig_zimbor", label = "Zimbor", category = "Story" },
    { name = "player_one", label = "Player One", category = "Story" },
    { name = "player_two", label = "Player Two", category = "Story" },
    { name = "player_zero", label = "Player Zero", category = "Story" },
    { name = "ig_agatha", label = "Agatha", category = "Story" },
    { name = "ig_avery", label = "Avery", category = "Story" },
    { name = "ig_brucie2", label = "Brucie2", category = "Story" },
    { name = "ig_thornton", label = "Thornton", category = "Story" },
    { name = "ig_tomcasino", label = "Tomcasino", category = "Story" },
    { name = "ig_vincent", label = "Vincent", category = "Story" },

}
